Update to datalist
siigdev/Travelbunny-Web pull request #5
Opened 2021-01-25 18:52 UTC by Nordico-team

I Tiago Rangel, brother of André Rangel, change this file to add the datalist.
It haves the Nordico list of citys, and provides a search to the citys.
PLEASE verify the code

2021-01-25 19:00 UTC, siigdev requested changes

2021-01-25 19:03 UTC, Nordico-team commented on src/components/landing_page/SearchBox.jsx
> + <Autocomplete
Okay!

2021-01-25 19:04 UTC, Nordico-team commented on src/components/landing_page/SearchBox.jsx
> +        onSearch={handleOnSearch}
Sorry, I don't delete them.
I was using a code demo.

2021-01-25 19:04 UTC, Nordico-team commented on src/components/landing_page/SearchBox.jsx
> +        onSearch={handleOnSearch}
I well delete it now!

2021-01-25 19:04 UTC, Nordico-team commented on src/components/landing_page/SearchBox.jsx
> +        onSearch={handleOnSearch}
For deliting

2021-01-25 19:06 UTC, Nordico-team commented on src/components/landing_page/SearchBox.jsx
> +        onSearch={handleOnSearch}
Deleted!

2021-01-25 19:08 UTC, Nordico-team commented on src/components/landing_page/SearchBox.jsx
> + <Autocomplete
Sorry, but how can I correct it?
(By Tiago Rangel)

2021-01-25 19:10 UTC, Nordico-team commented on src/components/landing_page/SearchBox.jsx
> + <Autocomplete
How, there is! On the other code, you don't close the > or the < on the first tag.
Sorry...

2021-01-25 19:11 UTC, Nordico-team commented on src/components/landing_page/SearchBox.jsx
> + <Autocomplete
I well try to correct it!

2021-01-25 19:31 UTC, Nordico-team commented on src/styles/main.scss
> +  cursor:pointer;
I've just added the cursor:pointer so the user know's that it is a place that he can click.

2021-02-27 10:27 UTC, Nordico-team commented
Closed
Too many time to respond

2021-02-27 10:27 UTC, closed without merging